[build]
  command = "npm run build"
  publish = "dist/"

[dev]
  autoLaunch = false
  command = "npm run parcel"
  port = 8888
  targetPort = 8887

[functions]
  directory = "api/"

[[redirects]]
  from = "/api/example"
  to = "/.netlify/functions/netlify"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
