# https://docs.gitlab.com/ee/ci/yaml/README.html
#
# 1. Verify Zeit domain and add CNAMEs that point to alias.zeit.co
# 2. Create token https://zeit.co/account/tokens
# 3. Add NOW_TOKEN variable at https://<<GITLAB_REPO>>/-/settings/ci_cd
# 4. Use --scope <<TEAM>> if deploying to team project

image: node:10-alpine

before_script:
  - node -v
  - npm -v
  - npm install -g --unsafe-perm now

deploy_staging:
  stage: deploy
  environment:
    name: staging
    url: https://<<STAGING_URL>>.com/
  only:
    - develop
  script:
    - now --token ${NOW_TOKEN} --prod --scope <<TEAM>>

deploy_production:
  stage: deploy
  environment:
    name: production
    url: https://<<PRODUCTION_URL>>.com/
  only:
    - master
  script:
    - now --token ${NOW_TOKEN} --prod --scope <<TEAM>> --local-config now.prod.json
